### ISSUE TITLE
rate-mirrors fails when mirror list times out

### ISSUE THREAD

**Issue by BirdDev** [westandskif/rate-mirrors#13]
Hi, I just tried the command `rate-mirrors --save=./mirrors arch --max-delay=21600` but it failed with the following output:
`
# STARTED AT: 2021-11-21 00:03:10.670412668 +01:00
# ARGS: rate-mirrors --save=./mirrors --entry-country DE arch --max-delay=3600
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.archlinux.org")), port: None, path: "/mirrors/status/json/", query: None, fragment: None }, source: TimedOut }', src/targets/archlinux.rs:48:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', src/main.rs:131:26
`
This seems to be caused by the arch website having a timeout. I also could not reach the page using my browser.
It took me some time to figure out the reason for this so I thought an error message would be nice.
Thanks!

**Comment by westandskif** [comment]
improved in [v0.6.0](https://github.com/westandskif/rate-mirrors/releases/tag/v0.6.0)
