### ISSUE TITLE
Support for Artix linux

### ISSUE THREAD

**Issue by BirdDev** [westandskif/rate-mirrors#14]
Hi I really like this project and would love to use it for artix linux, too.
It there any chance support will be added?
I would implement it myself but I don't know rust...
Thanks!

**Comment by westandskif** [comment]
support for artix linux has been added in [v0.6.0](https://github.com/westandskif/rate-mirrors/releases/tag/v0.6.0)

Please, let me know should you have any issues with it.
Or if this works fine and is helpful, may I ask to spread the word about it? :)

**Comment by BirdDev** [comment]
I just tried it out it works great!
Thank you very much!
I'll definitively tell my friends about it :)
