### ISSUE TITLE
Support for different branches on Manjaro

### ISSUE THREAD

**Issue by mattikan** [westandskif/rate-mirrors#15]
Hey, would it be possible to add support for branches different than stable on Manjaro? Currently I'm manually editing the mirrorlist-file after running this tool to replace the stable urls with unstable ones.

**Comment by westandskif** [comment]
hi @mattikan 
try the `branch` option like this: `rate-mirrors manjaro --branch=unstable`

**Comment by mattikan** [comment]
Damn, I thought I managed to look through all the documentation and help options. That's exactly what I was looking for. Thanks and apologies!
