### ISSUE TITLE
The --protocol option isn't working

### ISSUE THREAD

**Issue by Pound-Hash** [westandskif/rate-mirrors#16]
If I run the option, I'm presented with the same output I would receive if I just ran `rate-mirrors help'.

Specifically, I've tried running `rate-mirrors --protocol https arch`

I've also tried enclosing the `http` argument in quotes.

I've tried the command from both `fish` and `bash`.

The command works without the `--protocol` option.

- rate-mirrors config 0.6.0
- rate-mirrors-bin (AUR)

Cheers

**Comment by westandskif** [comment]
hi @Pound-Hash
try running `rate-mirrors --protocol=https arch`

**Comment by Pound-Hash** [comment]
Okay, that works. Thanks.

How would a user normally know whether to use an equals sign or a space for command line arguments?

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by westandskif** [comment]
@Pound-Hash this is a good question, I submitted an issue to rust's `structopt` repo, let's wait
