### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by xfzv** [westandskif/rate-mirrors#18]
https://github.com/westandskif/rate-mirrors/blob/d25d1cc742091f8c1649a51fdb22062b63ddb5d1/src/target_configs/archlinux.rs#L40

Should be `score_asc` instead of `store_asc`, right?

Keep up the good work :+1:

**Comment by westandskif** [comment]
Hi @xfzv Thank you! I'll fix this soon

**Comment by westandskif** [comment]
Fixed in [v0.6.2](https://github.com/westandskif/rate-mirrors/releases/tag/v0.6.2)
Already on AUR.
