### ISSUE TITLE
Warning at compile time

### ISSUE THREAD

**Issue by simonbcn** [westandskif/rate-mirrors#19]
```
....
warning: field is never read: `active`
--> src/targets/archlinux.rs:24:5
|
24 |     active: bool,
|     ^^^^^^^^^^^^
|
= note: `#[warn(dead_code)]` on by default
```

**Comment by westandskif** [comment]
Hi Simon,
No problem, I'll comment this one (_this "active" flag is what [ArchLinux Mirror Status](https://archlinux.org/mirrors/status/json/) provides, so I'm parsing this just in case it can be useful in the future_)
