### ISSUE TITLE
PKGBUILD needs fixing 

### ISSUE THREAD

**Issue by Rippanda12** [westandskif/rate-mirrors#32]
arch shouldnt be set to ANY it should be
```
arch=('x86_64' 'aarch64')
```
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rate-mirrors

**Comment by westandskif** [comment]
Why?
https://wiki.archlinux.org/title/PKGBUILD#arch says it's fine to have `any` set

**Comment by Rippanda12** [comment]
if i for example build this package on x86 pc and try to install it on arm itll install fine but the app wont work cus it was built on x86

**Comment by Rippanda12** [comment]
arch=('any') indicates the package can be built once on any architecture, **and once built, is architecture-independent in its compiled state** (shell scripts, fonts, themes, many types of extensions, etc.).

**Comment by Rippanda12** [comment]
that does not apply to this as this isnt a interpreted language but a compiled one

**Comment by westandskif** [comment]
thank you for elimination of illiteracy! :) done!
