### ISSUE TITLE
You dun broke it

### ISSUE THREAD

**Issue by LethalManBoob** [westandskif/rate-mirrors#46]
error: unexpected argument '--save' found

  tip: a similar argument exists: '--save-to-file'

**Comment by westandskif** [comment]
thank you for letting me know, it's fixed in v0.16.2

**Comment by BaconIsAVeg** [comment]
I hate to necro an old ticket, but it's also still referenced as `--save` when you run `rate-mirrors --help`

**Comment by westandskif** [comment]
hi @BaconIsAVeg 
`--save` option and `RATE_MIRRORS_SAVE` environment variable are correct and they are both in the `--help` and README.
While `--save-to-file` was a bug.

P.S. this ticket was about broken `--save` option: broken [here](https://github.com/westandskif/rate-mirrors/commit/f0f70bd3d0894dc9fda4b6d7445be1f661abc389#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdR228), look for `RATE_MIRRORS_SAVE`

**Comment by BaconIsAVeg** [comment]
> hi @BaconIsAVeg `--save` option and `RATE_MIRRORS_SAVE` environment variable are correct and they are both in the `--help` and README. While `--save-to-file` was a bug.
> 
> P.S. this ticket was about broken `--save` option: broken [here](https://github.com/westandskif/rate-mirrors/commit/f0f70bd3d0894dc9fda4b6d7445be1f661abc389#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdR228), look for `RATE_MIRRORS_SAVE`

Yes, I was confused because `rate-mirrors arch --save=foo` errors, but it's because you need to do `rate-mirrors --save=foo arch`

**Comment by westandskif** [comment]
Got it, thank you!
