### ISSUE TITLE
run rate-mirrors archlinuxcn, return error

### ISSUE THREAD

**Issue by windilt** [westandskif/rate-mirrors#50]
here is the error message

➜  ~ rate-mirrors archlinuxcn
# STARTED AT: 2023-08-20 10:33:04.779973302 +08:00
# ARGS: rate-mirrors archlinuxcn
Error: error sending request for url (https://raw.githubusercontent.com/archlinuxcn/mirrorlist-repo/master/archlinuxcn-mirrorlist): error trying to connect: tcp connect error: Connection refused (os error 111)

confirm I can open https://raw.githubusercontent.com/archlinuxcn/mirrorlist-repo/master/archlinuxcn-mirrorlist correctly by chromium

**Comment by westandskif** [comment]
Can you, please, try out [rate-mirrors-bin](https://aur.archlinux.org/packages/rate-mirrors-bin) version?
I didn't manage to reproduce it on:
* a mac
* dockerized arch + dynamically linked glibc (rate-mirrors)
* dockerized arch + statically linked musl (rate-mirrors-bin).

Question No2: Is there a chance that your chromium uses a proxy while the system doesn't?

**Comment by westandskif** [comment]
@windilt any updates on this?

**Comment by windilt** [comment]
westandskif，thanks a lot for your help.
I follow your comment change to rate-mirrors-bin version, same error
and this time I can't access https://raw.githubusercontent.com/archlinuxcn/mirrorlist-repo/master/archlinuxcn-mirrorlist with chromium or wget, maybe I opened proxy last time.
Is there a chance to use local mirrorlist to avoid Connection refused ? I can download mirrorlist with proxy but I don't want test speed with proxy. 

➜  ~ rate-mirrors archlinuxcn
# STARTED AT: 2023-08-28 08:46:38.231616716 +08:00
# ARGS: rate-mirrors archlinuxcn
Error: error sending request for url (https://raw.githubusercontent.com/archlinuxcn/mirrorlist-repo/master/archlinuxcn-mirrorlist): error trying to connect: tcp connect error: Connection refused (os error 111)
➜  ~ wget https://raw.githubusercontent.com/archlinuxcn/mirrorlist-repo/master/archlinuxcn-mirrorlist
--2023-08-28 08:47:42--  https://raw.githubusercontent.com/archlinuxcn/mirrorlist-repo/master/archlinuxcn-mirrorlist
已载入 CA 证书“/etc/ssl/certs/ca-certificates.crt”
正在解析主机 raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... 失败：拒绝连接。正在连接 raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... 失败：拒绝连接。

**Comment by windilt** [comment]
It is solved after I update my hosts with https://github.com/ineo6/hosts

**Comment by windilt** [comment]
It is solved after I update my hosts with https://github.com/ineo6/hosts
