### ISSUE TITLE
BlackArch support

### ISSUE THREAD

**Issue by D3vil0p3r** [westandskif/rate-mirrors#53]
Hello! I like this project and thank you for your work! Is it possible to have support for BlackArch repository? It could be very important for Cyber Security Professionals.

**Comment by westandskif** [comment]
hi @D3vil0p3r, thank you for your kind words! Sure, I can do it!
Is this the right source of mirrors? - https://github.com/BlackArch/blackarch/blob/master/mirror/mirror.lst

**Comment by D3vil0p3r** [comment]
Yes @westandskif It is.

**Comment by westandskif** [comment]
@D3vil0p3r [v0.17.0](https://github.com/westandskif/rate-mirrors/releases/tag/v0.17.0) added BlackArch support. Can you, please, check?

**Comment by D3vil0p3r** [comment]
Thank you very much @westandskif it works! I have one doubt: is it possible to sort the output by fastest mirrors and select the max number of mirrors to produce to output?

**Comment by westandskif** [comment]
@D3vil0p3r a regular user needs 1-2 mirrors, not all of them (testing all of them would cross out the main idea of rate-mirrors to take not more than ~ half a minute).

And even though the user should be fine with 1-2, it outputs a couple of dozens of them, **sorted** by speed. Can you, please, clarify the goal? To test each one of them somewhere on a server?

**Comment by D3vil0p3r** [comment]
In my case the goal is that I have a Linux OS installer that use reflector (only on Arch mirrors) that calculate the fastest 10 mirrors according to the country of the user that is installing the OS. Since the system will consider always the first mirror in the mirrorlist file, it could happen that sometimes a package in that mirror is not synced and can generate some errors. In that case my installer take the first mirror and move it at the end of the mirrorlist file and the old 2nd one becomes the 1st one that will be used. In this manner, I prevent several possible errors during the OS installation. Why max 10 mirrors? There is not a specific reason but usually I would like to be flexibile to set 5 or 10 or 15 mirrors (always according to the country of the user).

Why sorting by speed? Because Arch system considers always the first mirror in mirrorlist file, so, in this manner, the user can use the fastest mirror according to its location.

**Comment by westandskif** [comment]
@D3vil0p3r just so we are on the same page: `rate-mirrors` does sort mirrors by speed.

Please, check [algorithm](https://github.com/westandskif/rate-mirrors#algorithm) for details.
Also see `rate-mirrors --help` for generic options and `rate-mirrors arch --help` for arch-related options. 

> but I don't know if I can replicate all these arguments by rate-mirrors.

e.g. `--age 6`: what is it? if hours -> `rate-mirrors arch --max-delay=21600`

My suggestion is to pass options only if the defaults don't work for you. The tool is supposed to work without passing options.
So consider:

- [something similar to this](https://github.com/westandskif/rate-mirrors/discussions/44#discussioncomment-6200076) within installer before major downloads
- running simple `rate-mirrors blackarch` on before system update -- [example here](https://github.com/westandskif/rate-mirrors#example-of-everyday-use-on-arch-linux)
