### ISSUE TITLE
Manjaro support

### ISSUE THREAD

**Issue by dotiful** [westandskif/rate-mirrors#6]
Hi, thx for a nice tool. I use it on my arch hosts. Is there a way to add support for ranking [manjaro mirrors](https://repo.manjaro.org)?

**Comment by westandskif** [comment]
@dotiful I’ve checked and these are quite different + it doesn’t make sense to extend “rate-ARCH-mirrors”.
However this issue reveals that there may be a need on a tool like this, but not limited to arch mirrors.
Now I’m working on separating the core functionality of this tool and this will be available as a separate rust library + binary to “rate-mirrors”.

Once done, I’ll give you an update on this, providing a bash command to curl manjaro mirrors, take up to date and then feed the list of mirrors and countries to the new tool.

**Comment by westandskif** [comment]
hi @dotiful !
please check out the new version:
```
yay -S rate-mirrors-bin
# OR to build from sources
yay -S rate-mirrors

rate-mirrors manjaro
```

**Comment by dotiful** [comment]
@westandskif works like a charm 🔥, thanks a lot for your job!
