### ISSUE TITLE
Add Option to only Rank Tier 1 Mirrors

### ISSUE THREAD

**Issue by ptr1337** [westandskif/rate-mirrors#61]
Hi,

On CachyOS, we are using "rate-mirrors" as default for our online installation. This is used together with a script, called "cachyos-rate-mirrors", which ranks the CachyOS and Arch Mirrors.

Currently, users are running often in a problem, that mirrors have an "corrupted" archlinux keyring.

If there is any possibility, to add a option, which only ranks tier 1 mirrors - that would be helpful.

Thanks in advance!

**Comment by westandskif** [comment]
Hi, sure, let's add it!

**Comment by westandskif** [comment]
also pushed to AUR
